dist: xenial

language: generic

cache:
  apt: true
  timeout: 604800
  directories:
    # Cache stable Emacs binaries (saves 1min per job)
    - "$HOME/emacs"
    - ".cask/"
    - "$HOME/.emacs.d/.cask"

git:
  depth: 1

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
    - PATH="$HOME/bin:$HOME/.cask/bin:/tmp/emacs/bin:$PATH"
  matrix:
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26.2
    - EMACS_VERSION=26.3
    - EMACS_VERSION=master
    - EMACS_VERSION=26-prerelease
  allow_failures:
    - env: EMACS_VERSION=26-prerelease

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

before_script:
  - EMACS_MAJOR_VERSION="$(echo $EMACS_VERSION | cut -d '.' -f 1)"

script:
  - .ci/build.sh

notifications:
  email: false
